services:
  mongodb:
    image: mongo:latest
    container_name: ai_tutor_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./storage/mongo_data:/data/db
    restart: always

networks:
  default:
    name: ai_tutor_network
